name: Scan Docker Image from Webhook

on:
  repository_dispatch:
    types: [docker-push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Payload
        run: |
          echo "Event payload: ${{ toJson(github.event) }}"

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.client_payload.image_ref }}  # Dynamic image ref
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Report Failure
        if: failure()
        run: |
          echo "::error::Vulnerabilities detected in the image: ${{ github.event.client_payload.image_ref }}!"
          exit 1

      - name: Report Success
        if: success()
        run: |
          echo "✅ No critical vulnerabilities found in ${{ github.event.client_payload.image_ref }}."