 
name: Docker Image Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: my-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.43.0
          
      - name: Generate SBOM
        run: trivy image --format cyclonedx --output sbom.json my-app:latest
        
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
          
      - name: Scan for Critical Vulnerabilities (Block Pipeline)
        run: |
          trivy image \
            --exit-code 1 \
            --severity CRITICAL \
            --ignore-unfixed \
            --ignore-policy .trivyignore \
            my-app:latest
            
      - name: Scan for High Vulnerabilities (Warning Only)
        run: |
          trivy image \
            --severity HIGH \
            --ignore-unfixed \
            --ignore-policy .trivyignore \
            my-app:latest || echo "High vulnerabilities found but allowing pipeline to continue"
        continue-on-error: true
          
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Push Image to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME}}/my-app:latest