name: Scan Docker Image from Webhook

on:
  repository_dispatch:
    types: [docker-push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rishba07/myimages'  # Replace with your image
          format: 'table'
          exit-code: '1'  # Fail if vulnerabilities are found
          severity: 'HIGH,CRITICAL'

      - name: Report Failure
        if: failure()
        run: |
          echo "::error::Vulnerabilities detected in the image!"
          exit 1

      - name: Report Success
        if: success()
        run: |
          echo "✅ No critical vulnerabilities found."