name: Scan Docker Hub Image

on:
  workflow_dispatch:  # Manual trigger for testing
  repository_dispatch:  # Triggered by Docker Hub webhook
    types: [docker-push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_HUB_USERNAME }}/yourimage:latest'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Report Failure
        if: failure()
        run: |
          echo "::error::🛑 Vulnerabilities detected in the Docker image!"
          exit 1

      - name: Report Success
        if: success()
        run: |
          echo "✅ No critical vulnerabilities found."