name: Docker Image Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: my-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Scan for Any Vulnerability (Block Pipeline)
        run: |
          echo "🔍 Running Trivy scan on Docker image..."
          trivy image \
            --exit-code 1 \
            --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL \
            --ignore-unfixed \
            --ignore-policy .trivyignore \
            --format table \
            my-app:latest | tee trivy-results.log

      - name: Print Trivy Scan Logs
        if: failure()
        run: |
          echo "🚨 Trivy scan found vulnerabilities!"
          cat trivy-results.log

      - name: Upload Trivy Logs as Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-logs
          path: trivy-results.log
          
      - name: Login to Docker Hub (Only if scan passes)
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Push Image to Docker Hub (Only if scan passes)
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
